# Generated by Django 4.2.6 on 2023-10-09 02:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtfbody',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
